name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
        image: docker://markehammons/shackle-test-environments:opensuse-tw-latest

    steps:
    - uses: actions/checkout@v1
    - name: Compile plugin
      run: sbt compile
